### ISSUE TITLE
Augment Data Task

### ISSUE THREAD

**Issue by willschenk** [ellenguyen/CIS4496_EY#4]
So this is the data I found on RoboFlow, combined, and organized: 
https://github.com/ellenguyen/CIS4496_EY/tree/main/given/OtherTeamData 

And this is some code that I started for you: 
https://github.com/ellenguyen/CIS4496_EY/blob/main/AugmentDataTask.ipynb

**Comment by ellenguyen** [comment]
I can take over this 💪

**Comment by ellenguyen** [comment]
Check out my recent commit. I'm looking into semantic segmentation but have not decided to train on Roboflow or Rio since they are both in bounding box format.
