### ISSUE TITLE
Overlap Segment Anything with Rio Data 

### ISSUE THREAD

**Issue by willschenk** [ellenguyen/CIS4496_EY#5]
Resource: https://samgeo.gishub.org/examples/satellite/

**Comment by ellenguyen** [comment]
> Does anyone remember what this is called again? I've already asked our teacher like 3 times, I just forget.
Are you refering to the segmentation task or priming? Wasn't he also unfamiliar with priming?

> My idea of a finished product for this task, is a function that takes any image .tif or jpeg and returns a .txt annotation file of the segmentations. Also, maybe allow the function to input some sensitivity?
If you are targeting the segmentations while our submission data needs to return bounding box coordinates, would it make more sense to start with segmentation and then apply bounding boxes covering those segmentations? Idk just wondering lol

**Comment by willschenk** [comment]
> Are you refering to the segmentation task or priming? Wasn't he also unfamiliar with priming?
The segmentation task of `priming` / `building context` (no labels just polygons like this image) 
![Screenshot 2024-03-18 at 7 19 11 AM](https://github.com/ellenguyen/CIS4496_EY/assets/79812240/c97768a7-77a1-4ae0-975c-d6c933a09f0c) 

> If you are targeting the segmentations while our submission data needs to return bounding box coordinates, would it make more sense to start with segmentation and then apply bounding boxes covering those segmentations? 

Yes I agree. We can also make a function that converts segmentation -> bounding box if we need.
